# Kubernetes Secret manifest for AI-SMS Lead Platform
# Version: 1.0.0
# Purpose: Secure storage of sensitive configuration data for all microservices
# Security: OWASP, SOC 2 compliant with AES-256-GCM encryption

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-secrets
  namespace: app
  labels:
    app.kubernetes.io/name: ai-sms-platform
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: ai-sms-lead-platform
    app.kubernetes.io/managed-by: kustomize
    security.platform.io/encrypted: "true"
    security-tier: restricted
  annotations:
    # Encryption and key management
    encryption.platform.io/key-version: "v1"
    encryption.platform.io/provider: "aws-kms"
    encryption.platform.io/algorithm: "AES-256-GCM"
    
    # Automated rotation configuration
    rotation.platform.io/last-rotated: "2024-01-01T00:00:00Z"
    rotation.platform.io/schedule: "30d"
    rotation.platform.io/mode: "automated"
    
    # Security and compliance
    security.platform.io/audit-level: "high"
    security.platform.io/compliance: "SOC2,GDPR,CCPA"
    security.platform.io/backup-enabled: "true"
    
    # Access control
    auth.platform.io/required-groups: "platform-secrets-admin"
    rbac.platform.io/enforce-strict: "true"

data:
  # AI Service Configuration
  AI_SERVICE_API_KEY: "{{ base64_encoded_ai_service_key }}"
  OPENAI_API_KEY: "{{ base64_encoded_openai_key }}"
  
  # SMS Provider Configuration
  TWILIO_ACCOUNT_SID: "{{ base64_encoded_twilio_sid }}"
  TWILIO_AUTH_TOKEN: "{{ base64_encoded_twilio_token }}"
  MESSAGEBIRD_API_KEY: "{{ base64_encoded_messagebird_key }}"
  
  # Database Credentials
  REDIS_PASSWORD: "{{ base64_encoded_redis_password }}"
  MONGODB_URI: "{{ base64_encoded_mongodb_uri }}"
  POSTGRES_PASSWORD: "{{ base64_encoded_postgres_password }}"
  
  # Security and Encryption Keys
  JWT_SECRET: "{{ base64_encoded_jwt_secret }}"
  ENCRYPTION_KEY: "{{ base64_encoded_primary_encryption_key }}"
  BACKUP_ENCRYPTION_KEY: "{{ base64_encoded_backup_key }}"
  API_ENCRYPTION_KEY: "{{ base64_encoded_api_encryption_key }}"
  
  # Service-specific Configuration
  FORM_SERVICE_SECRET: "{{ base64_encoded_form_service_secret }}"
  ANALYTICS_SERVICE_KEY: "{{ base64_encoded_analytics_key }}"
  
  # Monitoring and Alerting
  ALERT_WEBHOOK_SECRET: "{{ base64_encoded_alert_webhook_secret }}"
  METRICS_ENCRYPTION_KEY: "{{ base64_encoded_metrics_key }}"

stringData:
  # Version tracking for key rotation
  KEY_VERSION: "v1"
  ROTATION_STATUS: "active"
  LAST_VALIDATION: "2024-01-01T00:00:00Z"